version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: provider

    binary: terraform-provider-nethost

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

archives:
  - id: provider

    builds:
      - provider

    formats:
      - zip

    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: terraform-provider-nethost_{{ .Version }}_SHA256SUMS

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  prerelease: auto